name: Deploy Node Project
on:
    workflow_dispatch:
        branches:
            - workflows
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Clone The Repository
              uses: actions/checkout@v5
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependancies
              run: npm ci
            - name: Run lint
              run: npm run lint

    build:
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependancies
              run: npm ci
            - name: Run Build
              run: npm run build
            - name: Deploy
              run: echo "Deploying...."

    test:
        runs-on: ubuntu-latest
        needs: [lint, build]
        steps:
            - name: Clone the repo
              uses: actions/checkout@v4
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependancies
              run: npm ci
            - name: Run test
              run: npm run test
